---
title: "UST 2021-2학기 현장연구"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true

---

# Day1 (2021.09.02)

## 강의목표

본 현장연구에서는 합성생물학 연구에 필요한 컴퓨터 관련 지식의 학습과 실습을 통해서 관련 데이터의 수집과 변환, 가시화 그리고 분석 능력을 습득하는 것에 목적이 있음. 특히 개인별 연구 주제에 따라서 필요한 컴퓨팅 기술들을 정리하고 각 기술들에 대해서 짧은 테크니컬 노트 수준의 보고서들을 작성하는데 목적이 있음.

## 운영방식

-   각 수강생들의 학위과정 동안의 주요 연구 주제와 연계한 수업임을 고려한 각 수강생별 연구주제 토의 및 선정
-   선정된 연구주제 중 컴퓨터 활용 관련한 기술을 정리하고 개인 수준별 타깃 기술 선정 및 목표를 수립함
-   선정된 타깃 기술에 대해서 수강생들의 실습 발표 위주의 진행하며 다른 수강생 및 지도교수의 코드 지도
-   필요한 경우 온라인 수업 툴을 활용함
-   연구 데이터 분석에 직접적으로 필요한 기술 위주로 진행하며 이를 위해 필요한 기반 기술 (리눅스 활용 등)은 필요한 경우 설명\
-   Docker 이미지 활용 (개인컴퓨터 활용 가능)
-   출석50%, 과제50%
-   각 수강생별로 본인의 연구와 관련된 간단한 도표 및 정리 문서 등이 수업의 목표에 따라서 과제로 나갈 수 있음
-   테크니컬 리포트는 길이에 따라서 1건 이상이 될 수도 있음
-   가능한 명확하고 짧은 길이의 리포트가 선호됨
-   과제물은 Rmarkdown을 활용한 pdf 형식의 문서로 제출함을 원칙으로 함

## 일정

-   1주 - 강의 개요 및 연구 주제 토의
-   2주 - 각 수강생들의 연구 주제 발표 및 컴퓨팅 기술 도출
-   3주 - 연구 주제에 따른 기술 워크플로우 작성 및 토의
-   4주 - 각 기술별 필요한 세부 컴퓨팅 기술 도출
-   5주 - 수강생별 담당 컴퓨팅 기술 선정
-   6주 - 기술 학습/실습/운영 위한 기반 docker 설치 및 학습
-   7주 - 수강생별 기술 학습 및 실습 1\~4
-   11주 - 테크니컬 노트 중간 정리\
-   12\~15주 - 수강생별 기술 학습 및 실습 5\~8
-   16주 - 테크니컬 노트 최종 정리
